name: Submit a New Gallery
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        ## 🖼️ Submit a New Ordinal Gallery

        Thanks for contributing to the Ord Galleries repository!

        - 📌 **The title of this issue will be used as the title of your gallery.** Please make it meaningful and precise. If the gallery represents a known collection, use the established name.
        - 🧾 **The gallery must already be inscribed on mainnet.**
        - 🛂 **Moderators review each submission.** Your gallery may be rejected or require changes.
        - 📖 All submissions are publicly visible and licensed under **[CC0 1.0 Universal](https://github.com/ordpool-space/ord-galleries/blob/main/LICENSE)**.

        Please fill out the form below carefully.

  - type: input
    id: galleryId
    attributes:
      label: Gallery Inscription ID
      description: The Inscription ID of the gallery that is being submitted.
      placeholder: "e.g. 01234567890abcdef01234567890abcdef01234567890abcdef01234567890abcdi0"
    validations:
      required: true

  - type: input
    id: previewId
    attributes:
      label: Preview Inscription ID (optional)
      description: An Inscription ID used as the gallery preview image. Ideally, this should be a scalable image (e.g. SVG, PNG, or HTML).
      placeholder: "e.g. 01234567890abcdef01234567890abcdef01234567890abcdef01234567890abcdi0"

  - type: input
    id: description
    attributes:
      label: Description (one line)
      description: An optional plain-text summary of the gallery or collection. No line breaks, no Markdown, no HTML.
      placeholder: "A collection of ..."

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose the most fitting category. You may select more than one. If none fit, select "other" or suggest a new one in a separate issue.
      multiple: true
      options:
        - art
        - photography
        - profile-picture
        - other

  - type: checkboxes
    id: terms
    attributes:
      label: License
      description: The entire content of this repository is licensed under CC0 1.0 Universal — https://github.com/ordpool-space/ord-galleries/blob/main/LICENSE. Please read the license before submitting.
      options:
        - label: I hereby agree to release all rights to the content to the public domain.
          required: true
