name: Convert Gallery Submission to Pull Request

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to process manually"
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  convert-issue-to-pr:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'submission'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Fetch issue data (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        id: fetch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          number="${{ inputs.issue_number }}"
          title=$(gh issue view "$number" --json title -q .title)
          body=$(gh issue view "$number" --json body -q .body)
          author=$(gh issue view "$number" --json author -q .author.login)
          echo "number=$number" >> $GITHUB_OUTPUT
          echo "title=$title" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "author=$author" >> $GITHUB_OUTPUT

      - name: Set issue data (automatic trigger)
        if: github.event_name == 'issues'
        id: fetch_auto
        run: |
          echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "author=${{ github.event.issue.user.login }}" >> $GITHUB_OUTPUT

      - name: Extract form values
        id: extract
        run: |
          get_field() {
            echo "$1" | sed -n "/^### ${2}/,/^### /{/^### /d;p}" | sed '/^[[:space:]]*$/d' | head -n1
          }

          body='${{ steps.fetch.outputs.body || steps.fetch_auto.outputs.body }}'

          echo "galleryId=$(get_field "$body" 'Gallery Inscription ID')" >> $GITHUB_OUTPUT
          echo "previewId=$(get_field "$body" 'Preview Inscription ID (optional)')" >> $GITHUB_OUTPUT
          echo "description=$(get_field "$body" 'Description (one line)')" >> $GITHUB_OUTPUT
          echo "category=$(get_field "$body" 'Category')" >> $GITHUB_OUTPUT

      - name: Build gallery file
        id: build
        run: |
          mkdir -p galleries

          number="${{ steps.fetch.outputs.number || steps.fetch_auto.outputs.number }}"
          title="${{ steps.fetch.outputs.title || steps.fetch_auto.outputs.title }}"
          author="${{ steps.fetch.outputs.author || steps.fetch_auto.outputs.author }}"

          galleryId="${{ steps.extract.outputs.galleryId }}"
          previewId="${{ steps.extract.outputs.previewId }}"
          description="${{ steps.extract.outputs.description }}"
          category="${{ steps.extract.outputs.category }}"

          safe_title=$(echo "$title" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/ /-/g' \
            | sed 's/[^a-z0-9-]//g')

          [ -z "$safe_title" ] && safe_title="gallery-${number}"
          filename="galleries/${safe_title}.yaml"

          {
            echo "galleryId: \"$galleryId\""
            echo "title: \"$title\""
            echo "author: \"$author\""
            [ -n "$previewId" ] && echo "previewId: \"$previewId\""
            [ -n "$description" ] && echo "description: \"$description\""
            [ -n "$category" ] && echo "category: \"$category\""
          } > "$filename"

          echo "filename=$filename" >> $GITHUB_OUTPUT
          echo "number=$number" >> $GITHUB_OUTPUT
          echo "title=$title" >> $GITHUB_OUTPUT
          echo "safe_title=$safe_title" >> $GITHUB_OUTPUT
          echo "galleryId=$galleryId" >> $GITHUB_OUTPUT
          echo "previewId=$previewId" >> $GITHUB_OUTPUT
          echo "description=$description" >> $GITHUB_OUTPUT
          echo "category=$category" >> $GITHUB_OUTPUT
          echo "author=$author" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add gallery from issue #${{ steps.build.outputs.number }} (${{ steps.build.outputs.safe_title }})"
          branch: "gallery-submission-${{ steps.build.outputs.number }}"
          title: "Add gallery from issue #${{ steps.build.outputs.number }} (${{ steps.build.outputs.safe_title }}): \"${{ steps.build.outputs.title }}\""
          body: |
            Closes #${{ steps.build.outputs.number }}

            Submitted by @${{ steps.build.outputs.author }}.

            **Gallery Details:**
            - **Title:** ${{ steps.build.outputs.title }}
            - **Filename:** ${{ steps.build.outputs.safe_title }}.yaml
            - **Gallery ID:** [${{ steps.build.outputs.galleryId }}](https://ordinals.com/inscription/${{ steps.build.outputs.galleryId }})
            - **Preview ID:** [${{ steps.build.outputs.previewId }}](https://ordinals.com/inscription/${{ steps.build.outputs.previewId }})
            - **Description:** ${{ steps.build.outputs.description }}
            - **Category:** ${{ steps.build.outputs.category }}
          labels: gallery
