name: Convert Gallery Submission to Pull Request

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to process manually"
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  convert-issue-to-pr:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'submission'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI (for manual fallback)
        if: github.event_name == 'workflow_dispatch'
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
           
      - name: Install YAML processor yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract issue data and build YAML
        id: build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p galleries

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            number="${{ inputs.issue_number }}"
            title=$(gh issue view "$number" --json title -q .title)
            body=$(gh issue view "$number" --json body -q .body)
            author=$(gh issue view "$number" --json author -q .author.login)
          else
            number="${{ github.event.issue.number }}"
            title="${{ github.event.issue.title }}"
            body="${{ github.event.issue.body }}"
            author="${{ github.event.issue.user.login }}"
          fi

          galleryId=$(echo "$body" | yq e '.galleryId' -)
          previewId=$(echo "$body" | yq e '.previewId' -)
          description=$(echo "$body" | yq e '.description' -)
          category=$(echo "$body" | yq e '.category' -)

          safe_title=$(echo "$title" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/ /-/g' \
            | sed 's/[^a-z0-9-]//g')

          [ -z "$safe_title" ] && safe_title="gallery-${number}"
          filename="galleries/${safe_title}.yaml"

          {
            echo "galleryId: \"$galleryId\""
            echo "title: \"$title\""
            echo "author: \"$author\""
            [ -n "$previewId" ] && echo "previewId: \"$previewId\""
            [ -n "$description" ] && echo "description: \"$description\""
            [ -n "$category" ] && echo "category: \"$category\""
          } > "$filename"

          echo "filename=$filename" >> $GITHUB_OUTPUT
          echo "title=$title" >> $GITHUB_OUTPUT
          echo "safe_title=$safe_title" >> $GITHUB_OUTPUT
          echo "galleryId=$galleryId" >> $GITHUB_OUTPUT
          echo "previewId=$previewId" >> $GITHUB_OUTPUT
          echo "description=$description" >> $GITHUB_OUTPUT
          echo "category=$category" >> $GITHUB_OUTPUT
          echo "author=$author" >> $GITHUB_OUTPUT
          echo "number=$number" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add gallery from issue #${{ steps.build.outputs.number }} (${{ steps.build.outputs.safe_title }})"
          branch: "gallery-submission-${{ steps.build.outputs.number }}"
          title: "Add gallery from issue #${{ steps.build.outputs.number }} (${{ steps.build.outputs.safe_title }}): \"${{ steps.build.outputs.title }}\""
          body: |
            Closes #${{ steps.build.outputs.number }}

            Submitted by @${{ steps.build.outputs.author }}.

            **Gallery Details:**
            - **Title:** ${{ steps.build.outputs.title }}
            - **Filename:** ${{ steps.build.outputs.safe_title }}.yaml
            - **Gallery ID:** [${{ steps.build.outputs.galleryId }}](https://ordinals.com/inscription/${{ steps.build.outputs.galleryId }})
            - **Preview ID:** [${{ steps.build.outputs.previewId }}](https://ordinals.com/inscription/${{ steps.build.outputs.previewId }})
            - **Description:** ${{ steps.build.outputs.description }}
            - **Category:** ${{ steps.build.outputs.category }}
          labels: gallery
